site_name: Apollo

site_url: https://apollo.tealingg.dev

repo_name: tealingg/apollo
repo_url: "https://github.com/tealingg/apollo"

plugins:
  - blog
  - tags

nav:
  - Introduction: index.md
  - Using Apollo:
    - using-apollo/installation.md
  - Blog:
    - blog/index.md

copyright: Made with ❤️ by tealingg using <b><a href="https://squidfunk.github.io/mkdocs-material">Material for MkDocs</a></b>.
extra:
  generator: false

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.sections
    - navigation.footer
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode